parameters:
    project_name: alexsys
    first_part: alex
    second_part: sys
    locale: es
    directories:
        global: '../web/upload/'
        relative: 'upload/'
        answerTask:
            files: 'answerTask/files/'