services:
    app.user.registration:
        class: UserBundle\Form\RegistrationFormType
        tags:
             - { name: form.type, alias: app_user_registration }
        arguments: ["@service_container"]